spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_dashboard
    username: saas_user
    password: saas_pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    clean-on-validation-error: true

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.pabloncf.saas: DEBUG
    org.flywaydb: DEBUG
