spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/saas_dashboard
    username: saas_app
    password: saas_app_pass
  flyway:
    url: jdbc:postgresql://postgres:5432/saas_dashboard
    user: saas_user
    password: saas_pass

logging:
  level:
    com.pabloncf.saas: INFO
